version: '3'

services:

  nginx:
    #build: ./docker-utils/nginx/
    image: nginx:latest

    ports:
      - "8888:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./docker-utils/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-utils/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-utils/logs/nginx:/var/log/nginx
      - ./:/var/www/html
    command: bash -c 'useradd -u 1000 local; nginx -g "daemon off;" && service nginx start && nginx -s reload'


  phpfpm:
    build: ./docker-utils/php/
   
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./docker-utils/php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker-utils/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker-utils/logs/php:/var/log/php
      - ./:/var/www/html

  db:
    image: mysql:5.7
  
    ports:
      - "3320:3306"

    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
      - ./dump/:/app/sqldump
      - ./db_local:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: globe_rp
      MYSQL_DATABASE: globe_d8
      MYSQL_USER: globe_u
      MYSQL_PASSWORD: globe123
